# Generated by Django 5.2.4 on 2025-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
    ]
