# Generated by Django 5.2.4 on 2025-09-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collab", "0004_projectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
