# Generated by Django 5.2.4 on 2025-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collab", "0004_projectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
