# Generated by Django 5.2.4 on 2025-10-22 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collab", "0005_task_priority"),
        ("collab", "0006_chatmessage"),
    ]

    operations = []
