# Generated by Django 5.2.4 on 2025-10-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collab", "0007_merge_0005_task_priority_0006_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
