# Generated by Django 5.2.4 on 2025-10-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collab", "0008_project_deleted_at_project_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_disabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
